site_amlak/Amlak/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('house.urls')),
     path('blog/', include('blog.urls')),
     path('contact/', include('contact.urls')),
     path('agent/', include('agent.urls')),
     path('accounts/', include('accounts.urls')),
    #   path("accounts/", include("django.contrib.auth.urls")),
     
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



admin.site.site_title = "پنل کاربری املاک سبز "
admin.site.site_header = "پنل ادمین املاک سبز "
admin.site.index_title = "پنل ادمین "
 

site_amlak/agent/urls.py
from django.urls import path
from . import views

app_name="agent"

urlpatterns = [
    path("",views.agent_list, name="agent_list"),
    
    path("<int:id>",views.agent_detail, name="agent_detail"),
]

site_amlak/blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path("",views.blog_list, name="blog_list"),
    path("<int:id>",views.blog_detail, name="blog_detail"),
]

site_amlak/house/urls.py
from django.urls import path
from . import views


app_name="house"

urlpatterns = [
    path("",views.House_list,name="house_list"),
    path("about/",views.about,name="about"),
    path("search",views.search,name="search"),
    path("house_list/",views.House_total_list,name="house_total_list"),
    path("<int:id>/",views.House_detail,name="house_detail"),
    
]

site_amlak/house/models.py
from django.db import models
from django.utils.translation import gettext as _
from agent.models import Agent
# Create your models here.
class House(models.Model):
    House_statue=[
        ("برای فروش","برای فروش"),
        ("برای اجاره","برای اجاره"),
    ]
    House_park=[
        ("دارد"," دارد "),
        ("ندارد"," ندارد  "),  
    ]
    name = models.CharField(max_length=100)
    desciption= models.CharField(_("توضیحات"),max_length=50)
    address= models.CharField(_("آدرس"),max_length=100)
    price= models.IntegerField(_("  قیمت  فروش"))
    mortgage= models.IntegerField(_("رهن") , null=True)
    rent_price= models.IntegerField(_("اجاره "), null=True)
    aria= models.IntegerField(_("مساحت به متر مربع"), default=0)
    room= models.IntegerField(_("تعداد خواب"),default=0)
    bathroom= models.IntegerField(_("تعداد حمام و دسشویی"),default=0)
    pub_date=models.DateField(_("تاریخ انتشار"),auto_now=False,auto_now_add=True)
    first_photo=models.ImageField(_("تصویر شاخص"),upload_to="house/",)
    second_photo=models.ImageField(_("تصویر دوم"),upload_to="house/" ,null=True,blank=True)
    third_photo=models.ImageField(_("تصویر سوم"),upload_to="house/",null=True,blank=True)
    Property_Type=models.ForeignKey("Property_Type",related_name="House", verbose_name=_("دسته بندی"), on_delete=models.CASCADE, null=True)
    house_park=models.CharField(_(" : وضعیت پارکینگ "),max_length=10,choices=House_park,default="ندارد")
    house_statue= models.CharField(_(" : وضعیت فروش "),max_length=10,choices=House_statue,default="برای فروش ")
    agent=models.ForeignKey(Agent,related_name="Agent", verbose_name=_(" مشاوره املاک"), on_delete=models.CASCADE, )
    
    class  Meta:
        
        managed = True
        verbose_name = ' خانه '
        verbose_name_plural = '  خانه ها   '
   
   
    def _value(self):
        if self.mortgage == '0':
            return u'%s' % (self.price)
        elif self.mortgage == '1':
            return u'%s' % (self.rent_price)
       
        
        
    def __str__(self) :
        return self.name
    
    
class Property_Type(models.Model):
    title=models.CharField(_("عنوان"),max_length=50)
    sluf=models.SlugField(_("عنوان لاتین"))
    published_at=models.DateField(_("تاریخ انتشار "),auto_now=False, auto_now_add=True)
    
    class  Meta:
        
        managed = True
        verbose_name = ' نوع خانه '
        verbose_name_plural = '  نوع خانه  ها   '
    
    def __str__(self) :
        return self.title
    

    
    

class ContactAgent(models.Model):
    house=models.ForeignKey(("House"),verbose_name=_("خانه"),related_name="houses", on_delete=models.CASCADE  )
    name=models.CharField(_("نام کاربر"),max_length=50)
    email=models.EmailField(_("آدرس ایمیل "),max_length=254)
    message=models.TextField(_("متن "))
    date=models.DateTimeField(_("تاریخ ثبت"), auto_now=False, auto_now_add=True ,null=True)
    agent=models.ForeignKey(("agent.Agent"),verbose_name=_("مشاور ملک"),related_name="agents", on_delete=models.CASCADE ,null=True )
    
    class  Meta:
        
        managed = True
        verbose_name = ' تماس با مشاور ملک '
        verbose_name_plural = '  تماس ها با مشاورین ملک ها   '
    def __str__(self) :
        return self.email
        
    

site_amlak/house/forms.py
from django import forms 

class ContactAgentForm(forms.Form):
    name=forms.CharField( max_length=50)
    email= forms.EmailField(max_length=254)
    message=forms.CharField(widget=forms.Textarea)

site_amlak/house/views.py
from django.shortcuts import render
from .models import House , ContactAgent
from django.core.paginator import Paginator
from blog.models import Blog 
from agent.models import Agent
from .forms import ContactAgentForm
from django.contrib import messages


# Create your views here.

def House_list(request):
    house_list= House.objects.all()
    blog_list= Blog.objects.all()
    agent_list= Agent.objects.all()
    
    
    context={
        "houses" : house_list ,
        "blogs":blog_list,
        "agents":agent_list,
        
        }
    return render(request,"houses/index.html", context )

def House_total_list(request):
    houses= House.objects.all()
    paginator = Paginator(houses, 3)  # Show 3 house per page.
    page_number = request.GET.get("page") 
    house_list = paginator.get_page(page_number)
    
    context={
        "house_list":house_list
    }
    
    return render(request,"houses/house_total_list.html",context)
  
def House_detail(request,id):
    house=House.objects.get(id= id)
    contact_agent=ContactAgent.objects.all().filter(house=house,)
    agent=house.agent
    
    if request.method == "POST":
        form=ContactAgentForm(request.POST)
        if form.is_valid():
            new_name=form.cleaned_data['name']
            new_email=form.cleaned_data['email']
    
            new_message=form.cleaned_data['message']
        
            new_contact=ContactAgent( house=house,name=new_name,email=new_email, message=new_message,agent=agent)
            new_contact.save()
            messages.success(request, 'پیام شما ثبت شد ')
            
      
    context={
        "house" : house ,
        "contacts":contact_agent ,
        
        }
    
    return render(request,"houses/detail.html", context )
        
def search(request):
    if request.method == "GET" :
        q1=request.GET.get("search")
        q2=request.GET.get("select1")
        q3=request.GET.get("select2")
        q4=request.GET.get("select3")
        q5=request.GET.get("select4")
        q6=request.GET.get("select5")
 
    house_list= House.objects.filter(name__icontains=q1,house_statue__icontains=q2,address__icontains=q3 ,                                      
                                     room__icontains=q4,bathroom__icontains=q5,price__range=(q6,1000000000000))
        
    return render(request , "houses/house_total_list.html",{"house_list":house_list})
    
def about(request):
    
    agent_list= Agent.objects.all()
       
    context={
        
        "agents":agent_list,
        
        }
           
    return render(request,'houses/about.html', context )
    
  

site_amlak/house/templates/houses/about.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<!DOCTYPE html>
<html lang="ar">


<body>





  <!--/ Intro Single star /-->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">بهترین سایت برای معامله ملک  در حوضه شهر اصفهان </h1>
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'house:house_list'  %}">صفحه اصلی </a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                درباره ما 
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--/ Intro Single End /-->

  <!--/ About Star /-->
  <section class="section-about">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="about-img-box">
            <img style="width: 100%; height:500px;" src={% static 'img/about.png' %} alt="" class="img-fluid">
          </div>
          <div class="sinse-box">
            <h3 class="sinse-title">املاک سبز 
              <span></span>
              <br> از سال 1403</h3>
            <p>فروش و اجاره </p>
          </div>
        </div>
        <div class="col-md-12 section-t8">
          <div class="row">
            <div class="col-md-6 col-lg-5">
              <img src={% static 'img/about.jpg' %} alt="" class="img-fluid">
            </div>
            <div class="col-lg-2  d-none d-lg-block">
              <div class="title-vertical d-flex justify-content-start">
                <span>املاک سبز اصفهان </span>
              </div>
            </div>
            <div dir="rtl" class="col-md-6 col-lg-5 section-md-t3">
              <div dir="rtl" class="title-box-d">
                <h3  dir="rtl" class="title-d">خدمات
                  <span dir="rtl" class="color-d">خرید و فروش  ملک</span> در 
                  <br> اصفهان</h3>
              </div>
              <p dir="rtl" class="color-text-a">
                خدمات فروش و اجاره ملک و املاک در حوضه استان اصفهان  را با ما انجام دهید . و همین ظور جدیدترین اطلاعات در حوضه ملک و املاک در استان اصفهان را از طریق ما با خبر شوید 
              </p>
              <p  dir="rtl" class="color-text-a">
              یکی دیگر از کار های ما مشاوره برای بازسازی خانه های قدیمی مخصوصا خانه های با بافت فرسوده میباشد 
              .
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ About End /-->

  <!--/ Team Star /-->
  <section class="section-agents section-t8">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="title-wrap d-flex justify-content-between">
            <div class="title-box">
              <h2 class="title-a">تیم مشاور املاک ما </h2>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        {% for agent in agents %}

        <div class="col-md-4">

          <div class="card-box-d">
            <div class="card-img-d">
              <img style="width: 100%; height:250px;" src="{{agent.image.url}}" alt="" class="img-d img-fluid">
            </div>
            <div class="card-overlay card-overlay-hover">
              <div class="card-header-d">
                <div class="card-title-d align-self-center">
                  <h3 class="title-d">
                    <a href="{% url 'agent:agent_detail' agent.id %}" class="link-two">{{agent.name}}
                      </a>
                  </h3>
                </div>
              </div>
              <div class="card-body-d">
                <p class="content-d color-text-a">
                  {{agent.description}}
                </p>
                <div class="info-agents color-a">
                  <p>
                    <strong>تلفن : </strong> {{agent.phone_number}}</p>
                  <p>
                    <strong>ایمیل : </strong> {{agent.email}}</p>
                </div>
              </div>
              <div class="card-footer-d">
                <div class="socials-footer d-flex justify-content-center">
                 
                  <a href="{% url 'agent:agent_detail' agent.id %}" class="link-a" >مشاهده اطلاعات بیشتر 
                    <span class="ion-ios-arrow-forward"></span> </a>

                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

       
    </div>
  </section>
  <!--/ Team End /-->





</body>
</html>
{% endblock content %}

site_amlak/house/templates/houses/house_total_list.html
{% extends "base.html" %}

{% load static %}


{% block content %}

<html>

<body>






  <!--/ Intro Single star /-->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">املاک  ما </h1>
            {% comment %} <span class="color-text-a">Grid Properties</span> {% endcomment %}
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'house:house_list'  %}">صفحه اصلی</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                املاک
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section>
  <!--/ Intro Single End /-->

  <!--/ Property Grid Star /-->
  <section class="property-grid grid">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="grid-option">
            <form>
              <select class="custom-select">
                <option selected>All</option>
                <option value="1">New to Old</option>
                <option value="2">For Rent</option>
                <option value="3">For Sale</option>
              </select>
            </form>
          </div>
        </div>
        {% for house in house_list %}
        
        <div class="col-md-4">
          <div class="card-box-a card-shadow">
            <div class="img-box-a">
              <img style="width: 100%; height: 250px;" src="{{house.first_photo.url}}" alt="" class="img-a img-fluid">
            </div>
            <div class="card-overlay">
              <div class="card-overlay-a-content">
                <div class="card-header-a">
                  <h2 class="card-title-a">
                    <a href="#">{{house.name}}
                      <br /> {{house.description}}</a>
                  </h2>
                </div>
                {% if house.price == 0 %}
                <div class="card-body-a">
                  <div class="price-box d-flex">
                    <span class="price-a">قیمت رهن یا فروش  |{{house.mortgage}}</span>
                  </div>
                  
                {% else %}
                <div class="card-body-a">
                  <div class="price-box d-flex">
                    <span class="price-a">قیمت رهن یا فروش  |{{house.price}}</span>
                  </div>
                  {% endif %}
                  <a href="{% url 'house:house_detail' house.id %}" class="link-a">مشاهده جزییات
                    <span class="ion-ios-arrow-forward"></span>
                  </a>
                </div>
                <div class="card-footer-a">
                  <ul class="card-info d-flex justify-content-around">
                    <li>
                      <h4 class="card-info-title">مساحت</h4>
                      <span>{{house.aria}}m
                        <sup>2</sup>
                      </span>
                    </li>
                    <li>
                      <h4 class="card-info-title">تعداد خواب </h4>
                      <span>{{house.room}}</span>
                    </li>
                    <li>
                      <h4 class="card-info-title">حمام و دسشویی</h4>
                      <span>{{house.bathroom}}</span>
                    </li>
                    <li>
                      <h4 class="card-info-title">پارکینگ</h4>
                      <span>{{house.house_park}}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

       
      </div>
      
      {% if house_list.has_other_pages %}

      <div class="row">
        <div class="col-sm-12">
          <nav class="pagination-a">
            <ul class="pagination justify-content-end">
              <li class="page-item disabled">
                {% if house_list.has_previous %}

                <a class="page-link" href="?page={{house_list.previous_page_number}}" tabindex="-1">
                  <span class="ion-ios-arrow-back"></span>
                </a>
              </li>
              {% endif %}

            

              {% for page in house_list.paginator.page_range %}

              {% if house_list.number == page %}
              <li class="page-item active">
                  <a class="page-link disabled" href="?page={{page}}">{{page}}</a>
                </li>
                {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{page}}">{{page}}</a>
                </li>

              {% endif %}
          
              {% endfor %}

              {% if house_list.has_next %}
              <li class="page-item next">
                <a class="page-link" href="?page={{house_list.next_page_number}}">
                  <span class="ion-ios-arrow-forward"></span>
                </a>
              </li>
              
              {% endif %}

            </ul>
          </nav>
        </div>
      </div>
      {% endif %}

    </div>
  </section>



</body>
</html>

{% endblock content %}

site_amlak/house/templates/houses/index.html
 {% extends "base.html" %}
 
 
 {% load static %}


 {% block content %}

  
 <!--/ Carousel Star /-->
 <div class="intro intro-carousel">
  <div id="carousel" class="owl-carousel owl-theme">
    {% for house in houses %}
     

    <div class="carousel-item-a intro-item bg-image" style="background-image: url({{house.first_photo.url}})">
      <div class="overlay overlay-a"></div>
      <div class="intro-content display-table">
        <div class="table-cell">
          <div class="container">
            <div class="row">
              <div class="col-lg-8">
                <div class="intro-body">
                  <p class="intro-title-top">{{house.address}}
                    <br> {{house.Property_Type}}</p>
                  <h1 class="intro-title mb-4">
                    <span class="color-b">{{house.id}}</span> {{house.name}}
                    </h1>
                  <p class="intro-subtitle intro-price">
                    <a href="{% url 'house:house_detail' house.id %}"><span class="price-a">قیمت : {{house.price}}</span></a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% comment %} <div class="carousel-item-a intro-item bg-image" style="background-image: url(img/slide-2.jpg)">
      <div class="overlay overlay-a"></div>
      <div class="intro-content display-table">
        <div class="table-cell">
          <div class="container">
            <div class="row">
              <div class="col-lg-8">
                <div class="intro-body">
                  <p class="intro-title-top">Doral, Florida
                    <br> 78345</p>
                  <h1 class="intro-title mb-4">
                    <span class="color-b">204 </span> Rino
                    <br> Venda Road Five</h1>
                  <p class="intro-subtitle intro-price">
                    <a href="#"><span class="price-a">rent | $ 12.000</span></a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item-a intro-item bg-image" style="background-image: url(img/slide-3.jpg)">
      <div class="overlay overlay-a"></div>
      <div class="intro-content display-table">
        <div class="table-cell">
          <div class="container">
            <div class="row">
              <div class="col-lg-8">
                <div class="intro-body">
                  <p class="intro-title-top">Doral, Florida
                    <br> 78345</p>
                  <h1 class="intro-title mb-4">
                    <span class="color-b">204 </span> Alira
                    <br> Roan Road One</h1>
                  <p class="intro-subtitle intro-price">
                    <a href="#"><span class="price-a">rent | $ 12.000</span></a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> {% endcomment %}
      {% comment %} {% endif %} {% endcomment %}
    {% endfor %}

  </div>
</div>
<!--/ Carousel end /-->

<!--/ Services Star /-->
<section class="section-services section-t8">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title-wrap d-flex justify-content-between">
          <div class="title-box">
            <h2 class="title-a">خدمات ما </h2>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="card-box-c foo">
          <div class="card-header-c d-flex">
            <div class="card-box-ico">
              <span class="fa fa-gamepad"></span>
            </div>
            <div class="card-title-c align-self-center">
              <h2 class="title-c">بازسازی  </h2>
            </div>
          </div>
          <div class="card-body-c">
            <p class="content-c">
              یکی از خدمات ما کمک به خانه های قدیمی برای بازسازی و تبدیل شدن به خانه مدرن و جدید میباشد .
            </p>
          </div>
         
        </div>
      </div>
      <div class="col-md-4">
        <div class="card-box-c foo">
          <div class="card-header-c d-flex">
            <div class="card-box-ico">
              <span class="fa fa-usd"></span>
            </div>
            <div class="card-title-c align-self-center">
              <h2 class="title-c">اجاره </h2>
            </div>
          </div>
          <div class="card-body-c">
            <p class="content-c">
              شما میتوانید برای اجاره دادن ملک خود و یا اجاره ملک دیگران با ما در ارتباط باشید .
            </p>
          </div>
         
        </div>
      </div>
      <div class="col-md-4">
        <div class="card-box-c foo">
          <div class="card-header-c d-flex">
            <div class="card-box-ico">
              <span class="fa fa-home"></span>
            </div>
            <div class="card-title-c align-self-center">
              <h2 class="title-c">فروش</h2>
            </div>
          </div>
          <div class="card-body-c">
            <p class="content-c">
              شما میتوانید برای فروش  ملک خود و یا خرید ملک دیگران با ما در ارتباط باشید 
            </p>
          </div>
         
        </div>
      </div>
    </div>
  </div>
</section>
<!--/ Services End /-->

<!--/ Property Star /-->
<section class="section-property section-t8">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title-wrap d-flex justify-content-between">
          <div class="title-box">
            <h2 class="title-a">پیشنهاد های جدید</h2>
          </div>
          <div class="title-link">
            <a href="{% url 'house:house_total_list'  %}">مشاهده همه 
              <span class="ion-ios-arrow-forward"></span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div id="property-carousel" class="owl-carousel owl-theme">
      {% for house in houses %}
      
      <div class="carousel-item-b">
        <div class="card-box-a card-shadow">
          <div class="img-box-a">
            <img style="width: 100%; height: 250px;"  src="{{house.first_photo.url}}" alt="" class="img-a img-fluid">
          </div>
          <div class="card-overlay">
            <div class="card-overlay-a-content">
              <div class="card-header-a">
                <h2 class="card-title-a">
                  <a href="{% url 'house:house_detail' house.id %}">{{house.name}}
                   </a>
                </h2>
              </div>
              <div class="card-body-a">
                <div class="price-box d-flex">
                  <span class="price-a">قیمت : | {{house.price}}</span>
                </div>
                <a href="{% url 'house:house_detail' house.id %}" class="link-a">مشاهده
                  <span class="ion-ios-arrow-forward"></span>
                </a>
              </div>
              <div class="card-footer-a">
                <ul class="card-info d-flex justify-content-around">
                  <li>
                    <h4 class="card-info-title">مساحت :</h4>
                    <span>{{house.aria}} m
                      <sup>2</sup>
                    </span>
                  </li>
                  <li>
                    <h4 class="card-info-title">خواب</h4>
                    <span>{{house.room}}</span>
                  </li>
                  <li>
                    <h4 class="card-info-title">حمام و دسشویی</h4>
                    <span>{{house.bathroom}}</span>
                  </li>
                  <li>
                    <h4 class="card-info-title">پارکینگ</h4>
                    <span>{{house.house_park}}</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
   
    </div>
  </div>
</section>
<!--/ Property End /-->

<!--/ Agents Star /-->
<section class="section-agents section-t8">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title-wrap d-flex justify-content-between">
          <div class="title-box">
            <h2 class="title-a">مشاوران املاک</h2>
          </div>
          <div class="title-link">
            <a href="{% url 'agent:agent_list'  %}">مشاهده همه
              <span class="ion-ios-arrow-forward"></span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      {% for agent in agents %}

      <div class="col-md-4">
        <div class="card-box-d">
          <div class="card-img-d">
            <img style="width: 100%; height:250px;"  src="{{agent.image.url}}" alt="" class="img-d img-fluid">
          </div>
          <div class="card-overlay card-overlay-hover">
            <div class="card-header-d">
              <div class="card-title-d align-self-center">
                <h3 class="title-d">
                  <a href="agent-single.html" class="link-two">{{agent.name}}
                    </a>
                </h3>
              </div>
            </div>
            <div class="card-body-d">
              <p class="content-d color-text-a">
                {{agent.description}}
              </p>
              <div class="info-agents color-a">
                <p>
                  <strong>تلفن : </strong> {{agent.phone_number}}</p>
                <p>
                  <strong>ایمیل : </strong> {{agent.email}}</p>
              </div>
            </div>
            <div class="card-footer-d">
              <div class="socials-footer d-flex justify-content-center">
                {% comment %} <ul class="list-inline">
                  <li class="list-inline-item">
                    <a href="#" class="link-one">
                      <i class="fa fa-facebook" aria-hidden="true"></i>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a href="#" class="link-one">
                      <i class="fa fa-twitter" aria-hidden="true"></i>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a href="#" class="link-one">
                      <i class="fa fa-instagram" aria-hidden="true"></i>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a href="#" class="link-one">
                      <i class="fa fa-pinterest-p" aria-hidden="true"></i>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a href="#" class="link-one">
                      <i class="fa fa-dribbble" aria-hidden="true"></i>
                    </a>
                  </li>
                </ul> {% endcomment %}
                <a href="{% url 'agent:agent_detail' agent.id %}" class="link-a" >مشاهده اطلاعات بیشتر 
                  <span class="ion-ios-arrow-forward"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
     
    </div>
  </div>
</section>
<!--/ Agents End /-->

<!--/ blog Star /-->
<section class="section-news section-t8">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title-wrap d-flex justify-content-between">
          <div class="title-box">
            <h2 class="title-a">جدید ترین بلاگ ها </h2>
          </div>
          <div class="title-link">
            <a href="{% url 'blog:blog_list'  %}">مشاهده همه
              <span class="ion-ios-arrow-forward"></span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div id="new-carousel" class="owl-carousel owl-theme">
      {% for blog in blogs %}
      <div class="carousel-item-c">
        <div class="card-box-b card-shadow news-box">
          {% if blog.image %}
          <div class="img-box-b">
            <img style="width: 100%; height: 200px;" src="{{blog.image.url}}" alt="" class="img-b img-fluid">
          </div>
          {% endif %}
          <div class="card-overlay">
            <div class="card-header-b">
              <div class="card-category-b">
                <a href="#" class="category-b">{{blog.category}}</a>
              </div>
              <div class="card-title-b">
                <h2 class="title-2">
                  <a href="{% url 'blog:blog_detail' blog.id %}">{{blog.title}}
                    </a>
                </h2>
              </div>
              <div class="card-date">
                <span class="date-b">{{blog.created_at}}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
   
    
    </div>
  </div>
</section>
<!--/ News End /-->




</html>

 
 {% endblock content %}