site_amlak/Amlak/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('house.urls')),
     path('blog/', include('blog.urls')),
     path('contact/', include('contact.urls')),
     path('agent/', include('agent.urls')),
     path('accounts/', include('accounts.urls')),
    #   path("accounts/", include("django.contrib.auth.urls")),
     
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



admin.site.site_title = "پنل کاربری املاک سبز "
admin.site.site_header = "پنل ادمین املاک سبز "
admin.site.index_title = "پنل ادمین "
 

site_amlak/agent/urls.py
from django.urls import path
from . import views

app_name="agent"

urlpatterns = [
    path("",views.agent_list, name="agent_list"),
    
    path("<int:id>",views.agent_detail, name="agent_detail"),
]

site_amlak/blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path("",views.blog_list, name="blog_list"),
    path("<int:id>",views.blog_detail, name="blog_detail"),
]

site_amlak/contact/urls.py
from django.urls import path
from . import views

app_name="contact"

urlpatterns = [
    path("",views.contact, name="contact_list"),
   
]

site_amlak/house/urls.py
from django.urls import path
from . import views


app_name="house"

urlpatterns = [
    path("",views.House_list,name="house_list"),
    path("about/",views.about,name="about"),
    path("search",views.search,name="search"),
    path("house_list/",views.House_total_list,name="house_total_list"),
    path("<int:id>/",views.House_detail,name="house_detail"),
    
]

site_amlak/templates/partials/footer.html
<!--/ footer Star /-->
<section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">املاک سبز</h3>
            </div>
            <div class="w-body-a">
              <p  class="w-text-a color-text-a">
               املاک سبز میتواند به شما کمک کند تا خانه خود را به بهترین قیمت اجاره دهید با به فروش برسانید 
              </p>
            </div>
            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  <span class="color-text-a">شماره تلفن :</span> 09303719895</li>
                <li  class="color-a">
                  <span  class="color-text-a"> ایمیل: </span >ali.nati080@gmail.com </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">خدمات ما </h3>
            </div>
            <div class="w-body-a">
              <div class="w-body-a">
                <ul class="list-unstyled">
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> فروش ملک
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> اجاره ملک
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> مشاوره بازسازی ملک
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> اطلاع رسانی راجب اخبار ملک 
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> مشاوره در زمینه خرید ملک در شهر اصفهان 
                  </li>
                 
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">شهر های ما :</h3>
            </div>
            <div class="w-body-a">
              <ul class="list-unstyled">
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> اصفهان
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> "شاهین شهر
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> سپاهان شهر
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i> بهارستان
                </li>
                <li class="item-list-a">
                  <i class="fa fa-angle-right"></i>خمینی شهر 
                </li>
                
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="nav-footer">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="{% url 'house:house_list'  %}">صفحه اصلی</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'house:about'  %}">درباره ما</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'house:house_total_list'  %}">املاک</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'blog:blog_list'  %}">بلاگ ها</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'contact:contact_list'  %}">ارتباط با ما</a>
              </li>
            </ul>
          </nav>
          <div class="socials-a">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-telegram" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-whatsapp" aria-hidden="true"></i>
                </a>
              </li>
              
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-instagram" aria-hidden="true"></i>
                </a>
              </li>
              
             
            </ul>
          </div>
      
          <div class="credits">
            
            Designed by ali nateghi
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--/ Footer End /-->

site_amlak/templates/partials/header.html
<div class="click-closed"></div>
<!--/ Form Search Star /-->
<div dir="rtl" class="box-collapse">
  <div class="title-box-d">
    <h3 class="title-d">ملک مورد نظر خود را پیدا کنید </h3>
  </div>
  <span class="close-box-collapse right-boxed ion-ios-close"></span>
  <div class="box-collapse-wrap form">
    <form class="form-a" method="GET" action="{% url 'house:search'  %}">
      <div class="row">
        <div class="col-md-12 mb-2">
          <div class="form-group">
            <label for="Type">اسم </label>
            <input name="search" type="text" class="form-control form-control-lg form-control-a" >
          </div>
        </div>
        <div class="col-md-6 mb-2">
          <div class="form-group">
            <label for="Type">وضعیت </label>
            <select name="select1" class="form-control form-control-lg form-control-a" id="Type">
              <option></option>
              <option>برای فروش</option>
              <option>برای اجاره</option>
             
            </select>
          </div>
        </div>
        <div class="col-md-6 mb-2">
          <div class="form-group">
            <label for="city">محدوده</label>
            <select  name="select2" class="form-control form-control-lg form-control-a" id="city">
              <option></option>
              <option>شیخ صدوق </option>
              <option>مرداویج</option>
              <option>خاقانی</option>
              <option>شهدا</option>
            </select>
          </div>
        </div>
        <div class="col-md-6 mb-2">
          <div class="form-group">
            <label for="bedrooms">تعداد خواب</label>
            <select name="select3" class="form-control form-control-lg form-control-a" id="bedrooms">
              <option></option>
              <option>1</option>
              <option>2</option>
              <option>3</option>
            </select>
          </div>
        </div>
        <div class="col-md-6 mb-2">
          <div class="form-group">
            <label for="bathrooms">حمام و دسشویی</label>
            <select name="select4" class="form-control form-control-lg form-control-a" id="bathrooms">
              <option></option>
              <option>1</option>
              <option>2</option>
              <option>3</option>
            </select>
          </div>
        </div>
        <div class="col-md-6 mb-2">
          <div class="form-group">
            <label for="price">قیمت از : (قیمت ها به میلیون تومان)</label>
            <select name="select5" class="form-control form-control-lg form-control-a" id="price">
              <option>0</option>
              <option>100</option>
              <option>500</option>
              <option>1000</option>
              <option>5000</option>
            </select>
          </div>
        </div>
        <div  class="col-md-12">
          <button  dir="rtl" type="submit" class="btn btn-b">پیدا کردن </button>
        </div>
      </div>
    </form>
  </div>
</div>
<!--/ Form Search End /-->

<!--/ Nav Star /-->
<nav  class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
  <div class="container">
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
      aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
     
    </button>
    <a class="navbar-brand text-brand" href="{% url 'house:house_list'  %}">املاک<span class="color-b"> سبز</span></a>
    <button type="button" class="btn btn-link nav-search navbar-toggle-box-collapse d-md-none" data-toggle="collapse"
      data-target="#navbarTogglerDemo01" aria-expanded="false">
      <span class="fa fa-search" aria-hidden="true"></span>
    </button>
    <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link " href="{% url 'house:house_list'  %}">صفحه اصلی </a>
        </li>
    
        <li class="nav-item">
          <a class="nav-link" href="{% url 'house:about'  %}">درباره ما </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'house:house_total_list'  %}">املاک</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:blog_list'  %}">بلاگ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'agent:agent_list'  %}"> مشاوران املاک </a>
        </li>
        
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact:contact_list'  %}">تماس با ما </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <p class="nav-link  " disabeld href="#">   {{ user.username}} سلام </p>
        </li>
        <li class="nav-item">
          <a class="nav-link  " disabeld href="{% url 'logout' %}"> خارج شدن</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'login'  %}">  ورود  </a>
        </li>
        {% endif %}
      </ul>
    </div>
    <button type="button" class="btn btn-b-n navbar-toggle-box-collapse d-none d-md-block" data-toggle="collapse"
      data-target="#navbarTogglerDemo01" aria-expanded="false">
      <span class="fa fa-search" aria-hidden="true"></span>
    </button>
  </div>
</nav>
<!--/ Nav End /-->